### ISSUE TITLE
Question about curation

### ISSUE THREAD

**Issue by melodykramer** [lolibrarian/NYPL-Emoji-Bot#9]
Hello!

I work at the Wikimedia Foundation and we're interested in forking your bot and using it for Commons Images. Are the emoji:image relationships manually curated? It appears that way, but I wanted to doublecheck.

Thanks in advance!

@melodykramer (mkramer@wikimedia.org / Twitter:@mkramer)

**Comment by lolibrarian** [comment]
Hi Melody! Yes, image relationships are manually curated for accuracy and quality control. Despite the great metadata work in Digital Collections, it doesn't always provide the precise level of detail needed to find some emoji. Hope you have fun with the project! —Lauren

**Comment by melodykramer** [comment]
Thanks Lauren! I'll post a link when we have ours up and running! - Mel
